apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app2-deployment.yaml
  - app2-svc.yaml
  - app2-ingress.yaml

replacements:
- source:
    kind: Ingress
    name: app1
    fieldPath: metadata.annotations.app/param-host
  targets:
  - select:
      kind: Ingress
      name: app1
    fieldPaths:
      - spec.rules.0.host